### ISSUE TITLE
Add a concrete example of the alternative for the deprecated DataFrame.last / first

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/pydata-amsterdam-pandas-sprint#3]
https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.last.html is deprecated. The deprecation message says:

> Please create a mask and filter using .loc instead

It would be nice to give an actual example of this to illustrate.

**Comment by Hestaron** [comment]
take
