### ISSUE TITLE
Mention alternative in the deprecation of Series.bool

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/pydata-amsterdam-pandas-sprint#4]
https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.bool.html is deprecated; it would be nice to explain a potential alternative.

**Comment by mcnoat** [comment]
~I'm currently looking into this one.~
**EDIT:** Abandonded this, because Joris told me that someone else at the sprint is already working on it.
