### ISSUE TITLE
Rewrite docstring in NumPy style

### ISSUE THREAD

**Issue by rhshadrach** [jorisvandenbossche/pydata-amsterdam-pandas-sprint#7]
pandas uses the [NumPy docstring style](https://numpydoc.readthedocs.io/en/latest/format.html). However the docstring for temp_set_attr is written using Google's docstring style:

https://github.com/pandas-dev/pandas/blob/d8d45223195aa16fce4fd8208e3ddedf7edf6a5c/pandas/core/common.py#L534-L544

This docstring should be rewritten using the NumPy style.

**Comment by stefmolin** [comment]
I recently created a [pre-commit hook that validates numpydoc format docstrings](https://numpydoc.readthedocs.io/en/latest/validation.html#docstring-validation-using-pre-commit-hook). It will be released in the next version of numpydoc, but is available in the release candidate now. Any interest in using it?

**Comment by rhshadrach** [comment]
@stefmolin - I think so; can you open up an issue for this on pandas.
